/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CardMidia: typeof import('./components/CardMidia.vue')['default']
    DropdownFilters: typeof import('./components/DropdownFilters.vue')['default']
    Favorite: typeof import('./components/Favorite.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SortingButtons: typeof import('./components/SortingButtons.vue')['default']
    StarRating: typeof import('./components/StarRating.vue')['default']
    ThemeButton: typeof import('./components/ThemeButton.vue')['default']
  }
}
